#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S2,     topLimitSW,          sensorI2CCustom)
#pragma config(Sensor, S3,     botLimitSW,          sensorI2CCustom)
#pragma config(Sensor, S4,     gyroSensor,          sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     conveyorMotor, tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     leftMotor,     tmotorNormal, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     elevatorMotor, tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     rightMotor,    tmotorNormal, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    leftArm,              tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    rightArm,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    leftWrist,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    flap,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    rightWrist,           tServoStandard)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define leftIRSensor            msensor_S4_1
#define sonarSensor             msensor_S4_2
#define rightIRSensor           msensor_S4_3
//#define gyroSensor              msensor_S4_4

#if 0
/// Copyright (c) Titan Robotics Club. All rights reserved.
///
/// <module name="ServoTest.c" />
///
/// <summary>
///     This module test the servo motor.
/// </summary>
///
/// <remarks>
///     Environment: RobotC for Lego Mindstorms NXT.
/// </remarks>
#endif

#include "JoystickDriver.c"
#include "..\ftclib\trcdefs.h"
#include "..\ftclib\dbgtrace.h"
#include "..\ftclib\joybtn.h"

#ifdef MOD_ID
    #undef MOD_ID
#endif
#define MOD_ID                  MOD_MAIN

//
// Trace info.
//
#define TRACE_MODULES           (MOD_MAIN)
#define TRACE_LEVEL             TASK
#define MSG_LEVEL               INFO

//
// Global data.
//
JOYBTN      g_JoyBtn1;
#if (_TARGET == "Robot")
JOYBTN      g_JoyBtn2;
#endif

/**
 *  This function handles the joystick button notification events.
 *
 *  @param joystickID Specifies the joystick the event was from.
 *  @param eventType Specifies the event type.
 *  @param eventID Specifies the event ID.
 *  @param fPressed Specifies the event is a press or a release.
 */
void
JoyBtnEvent(
    __in int  joystickID,
    __in int  eventType,
    __in int  eventID,
    __in bool fPressed
    )
{
    TFuncName("JoyBtnEvent");
    TLevel(EVENT);
    TEnterMsg(("Type=%x,ID=%x,On=%x", eventType, eventID, fPressed));

    if (joystickID == 1)
    {
        static int servoAngle = 0;

        if (eventType == JOYEVENT_BUTTON)
        {
            switch (eventID)
            {
                case Logitech_Btn1:
                    break;

                case Logitech_LB5:
                    servoAngle -= 10;
                    if (servoAngle < 0)
                    {
                        servoAngle = 0;
                    }
                    servo[leftArm] = servoAngle;
                    break;

                case Logitech_RB6:
                    servoAngle += 10;
                    if (servoAngle > 180)
                    {
                        servoAngle = 180;
                    }
                    servo[leftArm] = servoAngle;
                    break;

                default:
                    break;
            }
        }
        else if (eventType == JOYEVENT_TOPHAT)
        {
            switch (eventID)
            {
                case TopHat_Up:
                    break;

                default:
                    break;
            }
        }
    }
#if (_TARGET == "Robot")
    else if (joystickID == 2)
    {
        if (eventType == JOYEVENT_BUTTON)
        {
            switch (eventID)
            {
                case Logitech_Btn1:
                    break;

                case Logitech_Btn2:
                    break;

                case Logitech_Btn3:
                    break;

                case Logitech_Btn4:
                    break;

                case Logitech_LB5:
                    break;

                case Logitech_RB6:
                    break;

                default:
                    break;
            }
        }
        else if (eventType == JOYEVENT_TOPHAT)
        {
            switch (eventID)
            {
                case TopHat_Up:
                    break;

                case TopHat_Down:
                    break;

                default:
                    break;
            }
        }
    }
#endif

    TExit();
    return;
}   //JoyBtnEvent

/**
 *  This function initializes the robot and its subsystems.
 */
void
RobotInit()
{
    TFuncName("RobotInit");
    TLevel(INIT);
    TEnter();

    //
    // Initialize the input subsystems.
    //
    JoyBtnInit(g_JoyBtn1, 1, JOYBTNF_ENABLE_EVENTS);
#if (_TARGET == "Robot")
    JoyBtnInit(g_JoyBtn2, 2, JOYBTNF_ENABLE_EVENTS);
#endif

    TExit();
    return;
}   //RobotInit

/**
 *  This function processes all the high frequency tasks that needs to run
 *  more often than other tasks such as sensor integration tasks.
 */
void
HiFreqTasks()
{
    TFuncName("HiFreqTasks");
    TLevel(TASK);
    TEnter();
    TExit();
    return;
}   //HiFreqTasks

/**
 *  This function processes all the input tasks.
 */
void
InputTasks()
{
    TFuncName("InputTasks");
    TLevel(TASK);
    TEnter();

    JoyBtnTask(g_JoyBtn1);
#if (_TARGET == "Robot")
    JoyBtnTask(g_JoyBtn2);
#endif

    TExit();
    return;
}   //InputTasks

/**
 *  This function processes all the main tasks.
 */
void
MainTasks()
{
    TFuncName("MainTasks");
    TLevel(TASK);
    TEnter();
    TExit();
    return;
}   //MainTasks

/**
 *  This function processes all the output tasks. Output tasks are where all
 *  the actions are taking place. All other tasks are just changing states of
 *  various objects. There is no action taken until the output tasks.
 */
void
OutputTasks()
{
    TFuncName("OutputTasks");
    TLevel(TASK);
    TEnter();
    TExit();
    return;
}   //OutputTasks

/**
 *  This task is the program entry point.
 */
task main()
{
    long nextTime;
    long currTime;

    TraceInit(TRACE_MODULES, TRACE_LEVEL, MSG_LEVEL);

    //
    // The RobotInit function is provided by student code in TeleOpMain.h.
    //
    RobotInit();

    nextTime = nPgmTime;
    while (true)
    {
        currTime = nPgmTime;
        HiFreqTasks();
        if (currTime >= nextTime)
        {
            nextTime = currTime + LOOP_TIME;
            getJoystickSettings(joystick);
            //
            // The following functions are provided by student code in
            // TeleMain.h.
            //
            InputTasks();
            MainTasks();
            OutputTasks();
        }
        EndTimeSlice();
    }
}   //main
